export const ROUTE_URL = {
  HOME: "",
  DASHBOARD: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  ABOUT: "/about",
  CONTACT: "/contact",
  UI: "/ui",
  NOT_ALLOWED: "/not-allowed",
  SOCIAL_MEDIA_MANAGEMENT: "/social-media",
  CUSTOMERS: "/customers",
  FINANCE: {
    BASE: "/finance",
    SALES: {
      BASE: "/finance/sales/order",
      ADD: "/finance/sales/order/add",
      EDIT: "/finance/sales/order/edit/:orderId",
    },
    PURCHASE: "/finance/purchase",
    EXPENSES: "/finance/expenses",
    PAYMENTS: "/finance/payments",
    RECEIPTS: "/finance/receipts",
  },
  INVOICE_MANAGER: {
    BASE: "/invoice",
    CREATE: "/invoice/create",
    VIEW: "/invoice/view",
  },
  MASTER: {
    BASE: "/master",
    PRODUCTS: {
      BASE: "/master/products",
      LIST: "",
      EDIT: "edit/:id",
      ADD: "add",
    },
    FRAME_TYPES: {
      BASE: "/master/frame-types",
      LIST: "",
      EDIT: "edit/:id",
      ADD: "add",
    },
    GLASS_TYPES: {
      BASE: "/master/glass-types",
      LIST: "",
      EDIT: "edit/:id",
      ADD: "add",
    },
    MISC_CHARGES: {
      BASE: "/master/misc-charges",
      LIST: "",
      EDIT: "edit/:id",
      ADD: "add",
    },
    MOUNT_TYPES: {
      BASE: "/master/mount-types",
      LIST: "",
      EDIT: "edit/:id",
      ADD: "add",
    },
  },
  BILLS: "/bills",
  APP_SETTINGS: "/app-settings",
  TENANT_SETTINGS: "/tenant-settings",
  ADMIN: {
    BASE: "/admin",
    ORGANIZATION_UNITS: {
      BASE: "/organization-units",
      LIST: "",
      EDIT: "edit/:id",
      ADD: "add",
    },
    TENANT: {
      BASE: "/tenant",
      LIST: "",
      DETAIL: ":id",
      EDIT: "edit/:id",
      ADD: "add",
    },
    ROLE: {
      BASE: "/role",
      LIST: "",
      DETAIL: ":id",
      EDIT: "edit/:id",
      ADD: "add",
    },
    USER: {
      BASE: "/user",
      LIST: "",
      DETAIL: ":id",
      EDIT: "edit/:id",
      ADD: "add",
      PERMISSIONS: "permissions/:id",
    },
    SUBSCRIPTION_MANAGEMENT: "subscription-management",
  },
};
